export {default as Accueil_Container} from '../components/Accueil_Container/Accueil_Container';
export {default as Card} from '../components/Card/Card';
export {default as Banner} from '../components/Banner/Banner';
export { Banner_apropos } from './Banner/Banner';
export {default as Collapse} from '../components/Collapse/Collapse';
export {default as Carousel} from './Carousel/Carousel';
export {default as Details} from '../components/Details/Details';
export {default as Tag} from '../components/Tag/Tag';
export {default as Star_Favorite} from '../components/Star_Favorite/Star_Favorite';